### PR TITLE
Convert Decimal type results to float for Gremlin

### PR DESCRIPTION
**Pull request by michaelnchin**
Issue #, if available: #254

Description of changes:
- Fixed a issue where the presence of any `Decimal` type property values in Gremlin query results would prevent the graph widget from being displayed. `GremlinNetwork` now ensures that all `Decimal` type properties are converted to `float` before  we attempt to generate the graph widget.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by krlawrence — APPROVED** [review]
Looks good- did you do a test with the air routes data loaded by seed and a somewhat big query result? I'm curious if this impacts rendering performance much on either Gremlin Server or Neptune.

**Comment by krlawrence** [comment]
We should probably add a change-log entry for this.

**Comment by michaelnchin** [comment]
Added changelog entry. Tested performance of Gremlin network generation step on ~400 Air Routes results, found negligible (<1ms) difference in average duration between patched and non-patched version, on both Gremlin Server and Neptune.

**Review by krlawrence — APPROVED** [review]
Looks good

**Pull request merged**
